# Edite este arquivo para adicionar, remover ou organizar seus links.
title = "Início"
subtitle = "Centralizador de Links."

[[links]]
name = "GitHub"
url = "https://github.com"
description = "Projetos e repositórios"
group = "Desenvolvimento"
icon = "simple-icons:github"

[[links]]
name = "Gmail"
url = "https://mail.google.com"
description = "Caixa de entrada"
group = "Pessoal"

[[links]]
name = "Google Drive"
url = "https://drive.google.com"
description = "Arquivos e documentos"
group = "Pessoal"

[[links]]
name = "YouTube"
url = "https://youtube.com"
description = "Vídeos para assistir depois"
group = "Pessoal"

[[links]]
name = "MoeSeason Local"
url = "http://192.168.1.180:5173"
description = "Watch anime on localhost"
group = "Watch"
icon = "arcticons:anime-center"

[[links]]
name = "MoeSeason Web"
url = "http://ani.rodhfr.shop"
description = "Watch anime on web"
group = "Watch"
icon = "arcticons:anime-center"
